
import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Box, Flex, Grid, Theme, Text, Dialog, Button, TextField } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import NavBar from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Theme accentColor="sky" appearance="dark">
          <NavBar></NavBar>
          {children}
        </Theme>
      </body>
    </html>
  );
}
